export const jobs = [
  {
    id: 1,
    role: 'Frontend developer',
    slug: 'frontend-developer',
    salary: '$3k-$6k',
    location: 'England UK',
    url: 'https://www.randstad.ch/jobs/s-it/front-end-developer_geneve_39520491/?utm_source=indeed&igbTracker=640690341&utm_campaign=igb_advertising_IT&utm_medium=igb+cpc&utm_content=Front+End+Developer+%2817686%29+%5B0bcd2f08604ecabb_7b2e2cfe72295%5D',
    description:
      'We are looking for a front end developer with some experience in JavaScript, React/Angular technologies to join a dynamic team within a digital agency.',
    text: 'In this role, you will be responsible for developing and implementing user interface components using React.js concepts and workflow such as Redux, Flux, and Webpack.',
    info: 'Job Requirements',
    qualification: [
      'Minimum bachelor degree in computer science and any other relevant area.',
      'In-depth knowledge of JavaScript with at least 2-3 years of experience in web application development using : Angular/React.',
      'Familiarity with Vanilla JS/Typescript/ECMAScript 6, Javascript Patterns, HTML5/CSS3, Git.',
      'Interest in monitoring and training in new technologies.',
    ],
    title: 'Responsibilities',
    requirements: [
      'Develop complex web applications.',
      'Design and implement the architecture and interfaces of new functionalities.',
      'Define the guideline, technical choices and solutions for some specific projects in collaboration with the technical director.',
      'Accompany junior developers, help them solve blockers, and increase their skills through Code Review/Pair programming.',
    ],
  },
  {
    id: 2,
    role: 'PHP developer',
    slug: 'php-developer',
    salary: '$4k-$8k',
    location: 'Montreal Canada',
    url: 'https://perpetualsolution.com/job-detail.php?id=32',
    description:
      'Perpetual Solution is a Canadian owned and operated company specializing in Website Development and E-Commerce solutions.',
    text: 'We are looking for a php developer who is looking to augment their existing workload. You are passionate about coding, solving problems, creating solutions and you keep current on trends and technology.',
    info: 'Job Requirements',
    qualification: ['Proficient in PHP, mysql and ajax.'],
    title: 'Responsibilities',
    requirements: [
      'Ecommerce experience',
      'Ecommerce experience',
      'Good verbal and written communications skills',
      'One to three years of experience as a php backend developer',
    ],
  },
  {
    id: 3,
    role: 'UX/UI Designer',
    slug: 'designer',
    salary: '$3k-$7k',
    location: 'New York, USA',
    url: 'https://www.capitalonecareers.com/job/-/-/1732/30080466688',
    description:
      'The Consumer Card and Bank Experience Design team at Capital One is at the forefront of enriching our customers’ digital and physical experiences.',
    text: 'In this role, you will be collaborating with technology, product, and business teams to uncover customer and business needs, then translating them into engaging, simple, and intuitive design solutions and understandable concepts that evolve and enhance the product interface and experience',
    info: 'Job Requirements',
    qualification: [
      '​At least 1 year of (UX) User Experience and (UI) User Interface Design experience.',
      'Comfortable working with Product and Tech partners.',
      'Familiarity with design and prototyping tools, such as: Adobe Products, Sketch and/or Figma.',
    ],
    title: 'Responsibilities',
    requirements: [
      'Advocating for the customer through human centered design methods, including: discovery, research, ideation, whiteboard sessions, and user testing',
      'Supporting design-led workshops to engage and build alignment across different partners and teams',
      'Connecting with design community peers in service of learning, sharing, and teaching',
      'Working with partners and teams across various geographies',
    ],
  },
  {
    id: 4,
    role: 'Blockchain developer',
    slug: 'blockchain-developer',
    salary: '$8k-$12k',
    location: 'Germany',
    url: 'https://startupjoblist.com/job/blockchain-developer-solidity/',
    description:
      'The ideal candidate should be able to work with designers, back-end developers and with front-end web technologies',
    info: 'Job Requirements',
    text: 'We are looking for a motivated Solidity developer with coding experience, ideally with the same thirst for knowledge as we do. ',
    qualification: [
      'Minimum Qualification: Degree',
      'Experience Level: Senior level',
      'Experience Length: 5 years',
    ],
    title: 'Responsibilities',
    requirements: [
      'Practical and theoretical knowledge about software development',
      'Practical experience with Solidity development (incl. testing & deployment)',
      'Familiar with Hardhat, Remix, OpenZeppelin, Git, Ethers.js/Web3.js',
      'Experience with popular React.js workflows (such as Flux or Redux)',
      'Up to date with the latest developments in the scene',
    ],
  },
];
